name: Create Markdown Post

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  create-datetime-md:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Create Markdown Post
        run: |
          mkdir -p api/contents
          python3 .github/scripts/create_md_post.py
      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add api/contents/*.md
          git commit -m 'chore: create new post [skip ci]' || echo "No changes to commit"
          git push
